import logo from './logo.svg';
import './App.css';
import Projects from './Projects';
import { Routes, Route, Link } from "react-router-dom";

function App() {
  return (
    <div className='m-10 bg-blue-900 p-0 flex flex-col h-full font-mono'>
      <head>
        <title>Grant Rulon</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </head>

      <main className='mx-10 flex flex-col'>
        <div className='flex justify-center items-center flex-row mt-20'>
          <h1 className="text-5xl m-5 text-white font-bold">Grant Rulon</h1>
          <a href='#'>
            <img src='Rulon_Grant.jpg' className='rounded-full flex justify-start w-40 border-2 border-white hover:border-orange-700' />
          </a>
        </div>

        <div className='mt-10 border-y-2 border-x-0 border text-white text-lg sticky top-0'>
          <ul className='flex justify-center items-center flex-row'>
            <li className='mx-5 hover:text-orange-700'>
              <Link to="/">Home</Link>
            </li>
            <li className='mx-5 hover:text-orange-700'>
              <Link to="/contact">Contact Me</Link>
            </li>
            <li className='mx-5 hover:text-orange-700'>
              <Link to="/projects">Projects</Link>
            </li>
          </ul>
        </div>
      </main>

      <Routes>
        <Route path='/projects' element={<Projects/>}/>
      </Routes>

      <footer className='m-10 text-white'>
        <p>&#169; 2022 Grant Rulon</p>
      </footer>
    </div>
  );
}

export default App;
